[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "16.18.0"
  NPM_FLAGS = "--legacy-peer-deps"
[[plugins]]
package = "netlify-plugin-gatsby-cache"
